---
#dependencies
  - name: install iptables,iptables-persistent,ipset,jq
    apt: 
      name:
        - iptables
        - iptables-persistent
        - ipset
        - jq
      state: present

  - name: copy systemd dog_trainer.service
    copy: src=files/dog_trainer.service dest=/lib/systemd/system/dog_trainer.service
