---

- set_fact:
    build_env: 'qa'
    when: env is search("qa")
- set_fact:
    build_env: 'pro'
    when: env is search("pro")
- set_fact:
    build_env: 'dev'
    when: env is search("dev")

#manually checkout git repos until we create a public repo
#onto dog-vm-host/ansible/repos 
#ssh-kegen -p to create ~/.ssh/id_rsa w/no passphrase
#git git@bitbucket.org:republicwireless/jwt.git to add github key to known hosts for rebar3 checkout
#
#- name: copy dog_trainer repo
#  copy:
#    src: /ansible/repos/dog_trainer/
#    dest: /tmp/dog_trainer/
#- name: github key
#  command: ssh git@github.com
#
#- name: bitbucket key
#  command: ssh git@bitbucket.org
- name: create repos dir
  become: yes
  file:
    path: "{{ dog_trainer_repo }}"
    state: directory
    owner: vagrant
    group: vagrant

- debug: var=dog_trainer_version

- name: clone dog_trainer repo
  git:
    repo: git@github.com:Phonebooth/dog_trainer.git
    dest: "{{ dog_trainer_repo }}"
    version: "{{ dog_trainer_version }}"
    accept_hostkey: yes
    force: yes

- debug: var=dog_trainer_repo

- name: remove _build dir
  file:
    path: "{{ dog_trainer_repo }}/_build"
    state: absent

- file:
    src: "{{ dog_trainer_repo }}/config/sys.config.box"
    dest: "{{ dog_trainer_repo }}/config/sys.config"
    state: link

- name: execute rights on escript
  file:
    path: "{{ dog_trainer_repo }}/scripts/update_version.escript"
    mode: 0700

- name: execute rights on git_hash
  file:
    path: "{{ dog_trainer_repo }}/scripts/git_hash.sh"
    mode: 0700

- name: update version escript
  command: "scripts/update_version.escript config/sys.config.{{ dog_env }} {{ dog_env }}-{{ BUILD_ID }}"
  args:
    chdir: "{{ dog_trainer_repo }}"

- name: execute rights on rebar3
  file:
    path: "{{ dog_trainer_repo }}/rebar3"
    mode: 0700

- name: mix local.hex --force
  command: "mix local.hex --force" #will hang later if not '--force'

- name: mix local.rebar --force
  command: "mix local.rebar --force"

- name: add github.com to known_hosts
  lineinfile:
    create: yes
    path: ~/.ssh/known_hosts
    regexp:  "^github.com ssh-rsa"
    line: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

- name: add bitbucket.org to known_hosts
  lineinfile:
    create: yes
    path: ~/.ssh/known_hosts
    regexp:  "^bitbucket.org ssh-rsa"
    line: bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==

- name: run rebar3 as tar
  command: "{{ dog_trainer_repo }}/rebar3 as {{ env }} tar"
  args:
    chdir: "{{ dog_trainer_repo }}"

- name: get git hash
  shell: 'git rev-parse HEAD | tr -d "\n"'
  args:
    chdir: "{{ dog_trainer_repo }}"
  register: command_output

- set_fact:
    git_hash: "{{ command_output.stdout }}"

- debug: var=git_hash

- name: create archive link
  file:
    src: "{{ dog_trainer_repo }}/_build/box/rel/dog_trainer/dog_trainer-{{ git_hash }}.tar.gz"
    dest: "{{ dog_trainer_repo }}/_build/box/rel/dog_trainer/dog_trainer-local.tar.gz"
    state: link
