---
- name: install rabbitmq apt repo key
  shell: apt-key adv --keyserver "hkps://keys.openpgp.org" --recv-keys "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
  when: ansible_os_family == 'Debian'

## Cloudsmith: modern Erlang repository
- name: install erlang apt repo key
  shell: curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key | apt-key add -
  when: ansible_os_family == 'Debian'

## Cloudsmith: RabbitMQ repository
- name: install rabbitmq apt repo key
  shell: curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key | apt-key add -
  when: ansible_os_family == 'Debian'

- name: install rabbitmq apt repo
  shell: echo "deb https://dl.bintray.com/rabbitmq/debian bionic main" > /etc/apt/sources.list.d/bintray.rabbitmq.list
  when: ansible_os_family == 'Debian'

- name: install erlang packages
  apt:
    state: present
    update_cache: yes
    pkg:
    - erlang-base
    - erlang-asn1
    - erlang-crypto
    - erlang-eldap
    - erlang-ftp
    - erlang-inets
    - erlang-mnesia
    - erlang-os-mon
    - erlang-parsetools
    - erlang-public-key
    - erlang-runtime-tools
    - erlang-snmp
    - erlang-ssl
    - erlang-syntax-tools
    - erlang-tftp
    - erlang-tools
    - erlang-xmerl

- name: install rabbitmq
  apt: 
    name: rabbitmq-server={{ rabbitmq_apt_version }} 
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
