---
- hosts: containers
  become: yes
  tasks:
  - name: Add the group 'dog'
    group:
      name: dog
      state: present
      gid: 1040
  - name: Add the user 'dog'
    user:
      name: dog
      uid: 1040
      group: dog
  - name: add to sudo.d to account if applicable
    lineinfile: 
      dest: /etc/sudoers.d/dog 
      state: present 
      create: true 
      line: 'dog ALL = NOPASSWD: ALL'
      mode: 0440
