---
- name: remove apt-key from old erlang-solutions repo
  command: apt-key del A14F4FCA
  ignore_errors: yes

- name: remove old erlang-solutions repo package
  apt: name=erlang-solutions state=absent

- name: get erlang-solutions repo
  apt: deb=https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb state=present
    
- name: remove old repos    
  file: path="/etc/apt/sources.list.d/{{ item }}" state=absent
  with_items:
    - basho_riak.list
