---

- name: remove phonebooth-common-updates.repo
  file: path=/etc/yum.repos.d/phonebooth-common-updates.repo state=absent
  when: ansible_distribution_major_version == "6" or ansible_distribution == "Amazon"

- name: remove amzn-phonebooth-updates.repo
  file: path=/etc/yum.repos.d/amzn-phonebooth-updates.repo state=absent
  when: ansible_distribution_major_version == "6" or ansible_distribution == "Amazon"

  #- name: phonebooth-distro-updates.repo
  #  copy: src=phonebooth-distro-updates.repo dest=/etc/yum.repos.d/phonebooth-distro-updates.repo owner=root group=root mode=644
  #  when: ansible_distribution_major_version == "6"

- name: install EPEL repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
  when: ansible_distribution_major_version == "6"
  ignore_errors: yes

- name: fix SSL 3.0 issue w/repo
  command: sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo
  when: ansible_distribution_major_version == "6"

- name: install EPEL repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  when: ansible_distribution_major_version == "7"

- name: remove old ErlangSolutions repo  
  yum: name=https://packages.erlang-solutions.com/erlang-solutions-2.0-1.noarch.rpm state=absent
  ignore_errors: yes

- name: install ErlangSolutions repo  
  yum: name=https://packages.erlang-solutions.com/erlang-solutions-2.0-1.noarch.rpm
  ignore_errors: yes

- name: remove old repos    
  file: path="/etc/yum.repos.d/{{ item }}" state=absent
  with_items:
    - beats.repo 
    - scout.repo 
    - datadog.repo 
    - boundary.repo
    - rsyslog.repo
    - elastic.repo
    - basho_riak.repo
    - phonebooth-distro-updates.repo

- name: clean repo cache
  command: yum clean all
