---
- name: install iptables,iptables-persistent,ipset
  apt:
    name:
      - iptables
      - iptables-persistent
      - ipset
    state: present

- name: install ipsets-persistent plugin
  get_url: url=https://raw.githubusercontent.com/jordanrinke/ipsets-persistent/master/10-ipset dest=/usr/share/netfilter-persistent/plugins.d/10-ipset
  when: ansible_distribution_major_version != "12"

- name: set list of source ips
  set_fact:
    office_source_ips: [54.88.90.255/32,216.82.234.10/32,50.56.24.206/32,8.37.36.10/32,3.81.207.201/32,34.225.110.1/32,34.197.181.186/32,54.236.19.42/32,18.207.56.154/32] 

- name: Allow related and established connections
  template:
    src: iptables.j2
    dest: /etc/iptables/rules.v4
    mode: 0644
    force: yes

- name: restore iptables
  command: iptables-restore /etc/iptables/rules.v4
  become: yes
