---
- name: Restart monit
  service: name=monit state=restarted enabled=yes
  become: yes

- name: Reload monit
  command: /usr/bin/monit reload
  become: yes

- name: restart dog service
  systemd:
    daemon_reload: yes
    name: dog
    state: restarted
    enabled: yes        

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
