---
#dependencies
  - name: install iptables,iptables-persistent,ipset
    apt: 
      name:
        - iptables
        - iptables-persistent
        - ipset
      state: present
      update_cache: yes

  - name: check if /opt/dog/priv/dog.service exists
    stat:
      path: /opt/dog/priv/dog.service
    register: service_file
    tags:
    - upgrade
  
  - name: copy /opt/dog/priv/dog.service
    copy: 
      src: /opt/dog/priv/dog.service 
      dest: /lib/systemd/system/dog.service
    when: service_file.stat.exists
    tags:
    - upgrade
  
  - name: copy pbp dog.service
    copy: 
      src: dog.service 
      dest: /lib/systemd/system/dog.service
    when: not service_file.stat.exists
    tags:
    - upgrade
