---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: common_deploy
  include_role:
    name: common_deploy
  vars:
    app: dog_park
    s3_app: dog_park
    app_owner: dog_park
    env_specific_builds: True
    jenkins_job: dog_park
    extension: ".tar.gz"
    cluster: ""
    cluster_separator: ""
  tags:
  - upgrade
  when: env != "box"

- name: dog_park dir
  file:
    path: "/opt/dog_park.{{ git_hash }/dog_park"
    state: directory
  when: env == "box"

- name: target host gets archive from local directory
  become: true
  unarchive:
    src: "/ansible/repos/dog_park_agent/_build/box/rel/dog_park/dog_park-local.tar.gz"
    dest: "/opt/dog_park.{{ git_hash }}/"
    owner: dog_park
    group: dog_park
  when: env == "box"

- name: dog_park link
  file:
    src: "/opt/dog_park.{{ git_hash }}"
    dest: /opt/dog_park
    state: link
  when: env == "box"

- name: restart dog_park
  service:
    name: dog_park
    state: restarted
    enabled: yes
  tags:
  - upgrade
