---
- name: install curl
  apt:
    name: curl
    state: present

- name: install gnupg
  apt:
    name: gnupg 
    state: present

- name: download rabbitmq signing key
  command: curl -L https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc --output /tmp/rabbitmq-release-signing-key.asc

- name: import rabbitmq signing skey
  command: gpg --import /tmp/rabbitmq-release-signing-key.asc

## Cloudsmith: modern Erlang repository
- name: install erlang apt repo key
  shell: curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key | apt-key add -
  when: ansible_os_family == 'Debian'

## Cloudsmith: RabbitMQ repository
- name: install rabbitmq apt repo key
  shell: curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key | apt-key add -
  when: ansible_os_family == 'Debian'

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: rabbitmq repo
  copy:
    src: rabbitmq/cloudsmith.rabbitmq.list
    dest: /etc/apt/sources.list.d/cloudsmith.rabbitmq.list

- name: apt update
  shell: apt-get update -y

