---
#dependencies
  - name: check if ip_set.conf exists
    stat:
      path: /etc/modprobe.d/ip_set.conf 
    register: conf_result

  - name: increase ip_set max_sets
    shell: echo 'options ip_set max_sets=8192' > /etc/modprobe.d/ip_set.conf
    when: conf_result.stat.exists == False

  - name: unload ip_set
    command: /sbin/rmmod ip_set
    when: conf_result.stat.exists == False and ansible_distribution_major_version == "12" 

  - name: unload ip_set_hash_net
    command: /sbin/rmmod ip_set_hash_net
    when: conf_result.stat.exists == False and ansible_distribution_major_version == "12" 

  - name: unload xt_set
    command: /sbin/rmmod xt_set
    when: conf_result.stat.exists == False and ansible_distribution_major_version == "12" 

  - name: load ip_set
    command: /sbin/modprobe ip_set
    when: conf_result.stat.exists == False

  - name: load ip_set_hash_net
    command: /sbin/modprobe ip_set_hash_net
    when: conf_result.stat.exists == False

  - name: load xt_set
    command: /sbin/modprobe xt_set
    when: conf_result.stat.exists == False

  - name: create ipset config dir
    file:
      dest: /etc/iptables
      state: directory
      mode: 0700

  - name: install iptables,iptables-persistent,ipset
    apt: 
      name:
        - iptables
        - iptables-persistent
        - ipset
      state: present

  - name: install ipsets-persistent plugin
    file: src=ipsets-persistent_10-ipset dest=/usr/share/netfilter-persistent/plugins.d/10-ipset
    when: ansible_distribution_major_version != "12" 

  - name: copy systemd dog.service
    copy: src=dog.service dest=/lib/systemd/system/dog.service
    notify: systemd daemon-reload
    when: ansible_distribution_major_version != "12" 
    tags:
    - upgrade

  - name: copy ipsets-persistent plugin
    file: src=ipset-persistent_1.0_all.deb dest=/tmp/ipset-persistent_1.0_all.deb
    when: ansible_distribution_major_version == "12" 

  - name: install ipsets-persistent plugin
    become: yes
    command: dpkg -i /tmp/ipset-persistent_1.0_all.deb
    when: ansible_distribution_major_version == "12" 
  
  - name: copy upstart dog.conf
    copy: src=dog.upstart.conf dest=/etc/init/dog.conf mode=0744 owner=dog group=dog
    when: ansible_distribution_major_version == "12" 
    tags:
    - upgrade

  - name: stop and disable cphalod
    service:
      name: cphalod
      state: stopped
      enabled: false
    ignore_errors: yes
