---
#dependencies
  - name: install daemonize,iptables,iptables-ipv6,ipset
    yum: 
      name:
        - daemonize
        - iptables
        - iptables-ipv6
        - ipset 
      state: latest

  - name: check if ip_set.conf exists
    stat:
      path: /etc/modprobe.d/ip_set.conf 
    register: conf_result

  - name: increase ip_set max_sets
    shell: echo 'options ip_set max_sets=8192' > /etc/modprobe.d/ip_set.conf
    when: conf_result.stat.exists == False

  - name: load ip_set
    command: /sbin/modprobe ip_set
    when: conf_result.stat.exists == False

  - name: load ip_set_hash_net
    command: /sbin/modprobe ip_set_hash_net
    when: conf_result.stat.exists == False

  - name: load xt_set
    command: /sbin/modprobe xt_set
    when: conf_result.stat.exists == False

  - name: symlink ip_set
    file:
      src: /usr/sbin/ipset
      dest: /sbin/ipset
      state: link
      force: yes
    when: ansible_distribution_major_version != "7" 

  - name: create ipset config dir
    file:
      dest: /etc/iptables
      state: directory
      mode: 0700

  - name: symlink ipset.conf
    file:
      src: /etc/iptables/rules.ipset
      dest: /etc/sysconfig/ipset
      state: link
      force: yes

  - name: stop and disable cphalod
    service:
      name: cphalod
      state: stopped
      enabled: false

  - name: killall dog 
    shell: killall -s 2 -u dog 
    ignore_errors: yes
