- hosts: localhost
  vars:
    asdf_version: v0.8.0
    asdf_user: vagrant
  roles:
  - role: ansible-role-asdf
    asdf_plugins:
    - name: "erlang"
      versions: ["22.3.2"]
      global: "22.3.2"
    - name: "elixir"
      versions: ["1.9.4"]
      global: "1.9.4"
lxc config trust list
      #  tasks:
      #  - name: copy .asdf to /home/vagrant to avoid second build
      #    become: yes
      #    copy:
      #      remote_src: yes
      #      src: /root/.asdf
      #      dest: /home/vagrant/
      #      owner: vagrant
      #      group: vagrant
      #
      #  - name: change shims from root
      #    become: yes
      #    shell: sed -i 's/\/root\//\/home\/vagrant\//g' *
      #    args: 
      #      chdir: /home/vagrant/.asdf/shims/
