---
#- name: system proxy setup
#  import_playbook: proxy.yml

- hosts: "containers"
  become: yes
  gather_facts: yes
  tasks:
    - include_tasks: users.yml

- hosts: localhost
  connection: local
  roles:
    - { role: consul_ca_create }

- hosts: "containers"
  become: yes
  gather_facts: yes

  roles:
    - { role: consul_tls_cert }

      #- hosts: localhost
      #  tasks:
      #  - name: stop dog-agent containers to free memory for build
      #    command: lxc stop {{ item }}
      #    with_items:
      #      - dog-agent1
      #      - dog-agent2

- name: rabbitmq playbook
  import_playbook: rabbitmq.yml

- name: rethink playbook
  import_playbook: rethinkdb.yml

- name: dog_trainer_build
  import_playbook: dog_trainer_build.yml

- name: dog_trainer_deploy
  import_playbook: dog_trainer_deploy.yml

- name: dog_park_build
  import_playbook: dog_park_build.yml

- name: dog_park_deploy
  import_playbook: dog_park_deploy.yml

  #- hosts: localhost
  #  tasks:
  #  - name: start dog-agent containers
  #    command: lxc start {{ item }}
  #    with_items:
  #      - dog-agent1
  #      - dog-agent2

- name: dog_agent_build
  import_playbook: dog_agent_build.yml

- name: dog_agent_deploy
  import_playbook: dog_agent_deploy.yml
