---
- hosts: "server"
  gather_facts: yes
  become:  yes
  roles:
    - { role: rethinkdb}

  handlers:
  
    - name: restart rethinkdb
      service:
        name: rethinkdb
        state: restarted
