---
- name: create repos dir
  file:
    path: "{{ dog_park_repo }}"
    state: directory

- name: install nodesource repo
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_12.x | bash -

- name: install nodejs
  apt:
    name: nodejs=12.20.1-deb-1nodesource1
    state: present

- name: install yarn repo key
  become: yes
  shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

- name: install yarn repo
  become: yes
  shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

- name: install yarn
  shell: sudo apt install --no-install-recommends yarn

- name: clone dog_park repo
  ignore_errors: yes
  git:
    repo: git@bitbucket.org:republicwireless/dog_park.git
    dest: "{{ dog_park_repo }}"
    version: "{{ dog_park_version }}"

- name: setup npm/yarn proxy config
  shell: npm config set proxy http://192.168.145.1:3128; npm config set https-proxy http://192.168.145.1:3128; npm config set strict-ssl false npm config set registry “http://registry.npmjs.org/” npm –without-ssl –insecure install
  args:  
    chdir: "{{ dog_park_repo }}"

- name: yarn install
  shell: yarn install
  args:
    chdir: "{{ dog_park_repo }}"

- name: run build
  shell: REACT_APP_DOG_API_HOST='http://localhost:3000' yarn build dev
  args: 
    chdir: "{{ dog_park_repo }}"

- name: create archive
  delegate_to: 127.0.0.1
  connection: local
  shell: tar cf dog_park.tgz *
  args:
    chdir: "{{ dog_park_repo }}/build"
