---
#- debug: var=rethinkdb_config_template
- debug: var=rethinkdb_data_dir

- name: install rethinkdb repo
  command: wget http://download.rethinkdb.com/centos/6/x86_64/rethinkdb.repo -O /etc/yum.repos.d/rethinkdb.repo

- yum: name=rethinkdb state=present

- name: create '{{ rethinkdb_data_dir }}'
  file: path='{{ rethinkdb_data_dir }}' state=directory mode=0755 owner=rethinkdb group=rethinkdb

- name: create /var/log/rethinkdb
  file: path=/var/log/rethinkdb state=directory mode=0755 owner=rethinkdb group=rethinkdb

- name: Gather ec2 facts
  action: ec2_facts

- name: get public_ip
  set_fact:
    public_ip: "{{ ansible_ec2_public_ipv4 | default(omit) }}"
  when: ansible_ec2_user_data is defined

- name: get private_ip
  set_fact:
    private_ip: "{{ ansible_ec2_local_ipv4 | default(omit) }}"
  when: ansible_ec2_user_data is defined

- name: get public_ip
  set_fact:
    public_ip: "{{ ansible_default_ipv4.address  }}"
  when: not ansible_ec2_user_data

- name: get private_ip
  set_fact:
    private_ip: "{{ ansible_eth0.ipv4.address }}"
  when: not ansible_ec2_user_data and ansible_bond0 is not defined

- name: get private_ip
  set_fact:
    private_ip: "{{ ansible_bond0.ipv4.address }}"
  when: not ansible_ec2_user_data and ansible_eth0 is not defined

  #- name: copy rethinkdb config template
  #  template: src="{{ rethinkdb_config_template }}" dest=/etc/rethinkdb/instances.d/rethink.conf owner=root group=root mode=600

- name: /etc/monit.d/rethinkdb
  copy: src=rethinkdb.monit dest=/etc/monit.d/rethinkdb owner=root group=root mode=600

- service: name=rethinkdb state=restarted enabled=yes

- name: install rethinkdb python package
  command: /usr/local/bin/pip2.7 install rethinkdb
